### ISSUE TITLE
No objects and no namespace options under marker_array

### ISSUE THREAD

**Issue by Wanja93** [kostaskonkk/datmo#1]
Hello Kostas, awesome work. 
I managed to start the launch file, everything seems to work. Also with the rqt_graph /datmo seems to listen to my /scan message and publish /marker_array, except the /link_laser. But with rviz I can't find anything under MarkerArray and the submenu Namespace, no objects are recognized, unlike your demo.  Do you know what I am missing for objects to be recognized? As another launch file I only use the one from RpLidar A1 for the /scan. 

![rviz_screenshot_2020_03_21-12_43_10](https://user-images.githubusercontent.com/61310359/77225702-c9d6de80-6b71-11ea-9cd6-0770018bac1b.png)

**Comment by kostaskonkk** [comment]
Hello Wanja,
can you change the variable "world frame" to "laser" from "world", in the launch file and see if that helps?

**Comment by Wanja93** [comment]
Cool, that solve my problem.
