### ISSUE TITLE
how to debug this project by vscode?

### ISSUE THREAD

**Issue by ryontang** [kostaskonkk/datmo#2]
i am so sorry, when i use vscode to dubug this project: 

1. i use rosplay to run overtakes.bag, and bebug the executable file of datmo, 

2. but in function callback() it always remind me of "No transform could be found between base_link and map"

so my question is how can i debug this project, thanks a lot! looking forward your reply!

`if (tf_listener.canTransform(world_frame, lidar_frame, ros::Time())) // during debug failed to entering the code in if`

**Comment by kostaskonkk** [comment]
Hi and thanks a lot for using my package! :)
You can get a demo of the package by running
`roslaunch datmo example.launch bag:=overtakes`
The launch file does not only launch rosbag_play, but also a transform publisher and an instance of Rviz!
If you ever run into transform problems again remember that the command
`rosrun rqt_tf_tree rqt_tf_tree` 
is your friend!
I hope that this helps you solve your problem, if you have anymore questions or suggestions, feel free to open another issue! :)

**Comment by ryontang** [comment]
Hi, thanks for you reply and your share for this brilliant perception project, i don't  know whether i express my problem clearly. Actually the demo of launch file can run successfully, but i wanna use vscode to debug the code of this project to see the data structure of Tracking algorithm in detail.

In order to debug this project in vscode i made some changes in example.launch:
![image](https://user-images.githubusercontent.com/39891618/94690862-332a7c00-0363-11eb-91ed-096c822c93f2.png)

but i failed to do that for the debug breakpoints can't enter if-structure :

![image](https://user-images.githubusercontent.com/39891618/94692066-ae406200-0364-11eb-8913-06e0c1d29777.png)


The program cannot enter the if-structure and skip to else-structure:
![image](https://user-images.githubusercontent.com/39891618/94692268-f069a380-0364-11eb-9c72-0074f5ee2551.png)

**Comment by kostaskonkk** [comment]
When you comment out the  lines:
` <param name="lidar_frame" value="laser" /> 
 <param name="world_frame" value="map" /> `
then the default values are loaded which are not correct for the context of this specific bagfile.

To get a better view of this problem you can try the following two steps:
1. First find what values the parameters have:
`rosparam get /datmo/lidar_frame 
rosparam get /datmo/world_frame `
and then check if those transformations frames exist in the output of the tf_tree, which you get by running:
`rosrun rqt_tf_tree rqt_tf_tree`.

**Comment by ryontang** [comment]
Thanks a lot, my problem solved. 
As you indicated maybe some problem with the parameters of lidar_frame and world_frame, and i just modified the parameters lidar_frame from "base_link" to "laser" in constructor function of class Datmo, and loaded other parameters in example.launch of package datmo directly in constructor function instead of  using the way of rosparam load. 
After taking the measures mentioned above , the debugging function works normally.
![image](https://user-images.githubusercontent.com/39891618/94820505-1f4e4b00-0433-11eb-8611-8059c7ca1edd.png)

**Comment by kostaskonkk** [comment]
I am very happy that I have helped you! Feel free to ask me more questions and pls open a pull request if you implement any nice new feature! :)
